name: Android CI

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "0"
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create version tag
      id: create_tag
      run: |
        app=$(./gradlew -q printAppName)
        ver=$(./gradlew -q printAppVersion)
        tag=release-$ver-$(date +%Y%m%d-%H%M%S)
        apkreleaseuname=$app-$ver-release-unsigned.apk
        apkreleasename=$app-$ver-signedRelease.apk
        apkdebugname=$app-$ver-debug.apk
        apkreleaseupath=./app/build/outputs/apk/release/$app-$ver-release-unsigned.apk
        apkreleasenpath=./app/build/outputs/apk/signedRelease/$app-$ver-signedRelease.apk
        apkdebugpath=./app/build/outputs/apk/debug/$app-$ver-debug.apk
        echo "ver=$ver" >> $GITHUB_OUTPUT
        echo "tag=$tag" >> $GITHUB_OUTPUT
        echo "apkreleaseuname=$apkreleaseuname" >> $GITHUB_OUTPUT
        echo "apkreleasename=$apkreleasename" >> $GITHUB_OUTPUT
        echo "apkdebugname=$apkdebugname" >> $GITHUB_OUTPUT
        echo "apkreleaseupath=$apkreleaseupath" >> $GITHUB_OUTPUT
        echo "apkreleasepath=$apkreleasepath" >> $GITHUB_OUTPUT
        echo "apkdebugpath=$apkdebugpath" >> $GITHUB_OUTPUT

    - name: Create signing info
      id: create_signing
      run: |
        app=$(./gradlew -q printAppName)
        echo "${{ secrets.JKS }}" | base64 --decode > ./${ApplicationName}.jks
        echo -n "keystore=${ApplicationName}.jks" > ./${ApplicationName}.signing
        echo -n "${{ secrets.JKS_PWD }}" >> ./${ApplicationName}.signing
        echo -n "${{ secrets.JKS_KEY_ALIAS }}" >> ./${ApplicationName}.signing
        echo -n "${{ secrets.JKS_KEY_PWD }}" >> ./${ApplicationName}.signing
      shell: bash
      env:
        JKS: ${{ secrets.JKS}}
        JKS_PWD: ${{ secrets.JKS_PWD}}
        JKS_KEY_ALIAS: ${{ secrets.JKS_KEY_ALIAS}}
        JKS_KEY_PWD: ${{ secrets.JKS_KEY_PWD}}

    - name: Create Release
      id: create_release
      uses: comnoco/create-release-action@v2.0.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: ${{ steps.create_tag.outputs.tag }}
        draft: false
        prerelease: false
    - name: Create artifact files
      run: |
        mkdir info
        echo "${{ steps.create_release.outputs.id }}" > info/release_id
        echo "${{ steps.create_release.outputs.upload_url }}" > info/upload_url
    - uses: actions/upload-artifact@v1
      with:
        name: info
        path: info

  build:
    name: Build Release
    needs: [release]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "0"
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create version tag
      id: create_tag
      run: |
        app=$(./gradlew -q printAppName)
        ver=$(./gradlew -q printAppVersion)
        tag=release-$ver-$(date +%Y%m%d-%H%M%S)
        apkreleaseuname=$app-$ver-release-unsigned.apk
        apkreleasename=$app-$ver-signedRelease.apk
        apkdebugname=$app-$ver-debug.apk
        apkreleaseupath=./app/build/outputs/apk/release/$app-$ver-release-unsigned.apk
        apkreleasenpath=./app/build/outputs/apk/signedRelease/$app-$ver-signedRelease.apk
        apkdebugpath=./app/build/outputs/apk/debug/$app-$ver-debug.apk
        echo "ver=$ver" >> $GITHUB_OUTPUT
        echo "tag=$tag" >> $GITHUB_OUTPUT
        echo "apkreleaseuname=$apkreleaseuname" >> $GITHUB_OUTPUT
        echo "apkreleasename=$apkreleasename" >> $GITHUB_OUTPUT
        echo "apkdebugname=$apkdebugname" >> $GITHUB_OUTPUT
        echo "apkreleaseupath=$apkreleaseupath" >> $GITHUB_OUTPUT
        echo "apkreleasepath=$apkreleasepath" >> $GITHUB_OUTPUT
        echo "apkdebugpath=$apkdebugpath" >> $GITHUB_OUTPUT

    - name: Create signing info
      id: create_signing
      run: |
        app=$(./gradlew -q printAppName)
        echo "${{ secrets.JKS }}" | base64 --decode > ./${ApplicationName}.jks
        echo -n "keystore=${ApplicationName}.jks" > ./${ApplicationName}.signing
        echo -n "${{ secrets.JKS_PWD }}" >> ./${ApplicationName}.signing
        echo -n "${{ secrets.JKS_KEY_ALIAS }}" >> ./${ApplicationName}.signing
        echo -n "${{ secrets.JKS_KEY_PWD }}" >> ./${ApplicationName}.signing
      shell: bash
      env:
        JKS: ${{ secrets.JKS}}
        JKS_PWD: ${{ secrets.JKS_PWD}}
        JKS_KEY_ALIAS: ${{ secrets.JKS_KEY_ALIAS}}
        JKS_KEY_PWD: ${{ secrets.JKS_KEY_PWD}}

    - uses: actions/download-artifact@v1
      with:
        name: info
    - name: Set upload_url
      id: upload_info
      run: |
        upload_url=$(cat info/upload_url)
        echo "upload_url=$upload_url" >> $GITHUB_OUTPUT

    - name: Build with Gradle
      run: ./gradlew --warning-mode all build

    - name: Display artifacts
      run: find . -name '*.apk'
      working-directory: .

    - name: Upload signed release
      uses: shogo82148/actions-upload-release-asset@v1.7.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.upload_info.outputs.upload_url }}
        asset_path: ${{ steps.create_tag.outputs.apkreleasepath }}
        asset_name: ${{ steps.create_tag.outputs.apkreleasename }}
        asset_content_type: application/vnd.android.package-archive

    - name: Upload release
      uses: shogo82148/actions-upload-release-asset@v1.7.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.upload_info.outputs.upload_url }}
        asset_path: ${{ steps.create_tag.outputs.apkreleaseupath }}
        asset_name: ${{ steps.create_tag.outputs.apkreleaseuname }}
        asset_content_type: application/vnd.android.package-archive

    - name: Upload debug
      uses: shogo82148/actions-upload-release-asset@v1.7.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.upload_info.outputs.upload_url }}
        asset_path: ${{ steps.create_tag.outputs.apkdebugpath }}
        asset_name: ${{ steps.create_tag.outputs.apkdebugname }}
        asset_content_type: application/vnd.android.package-archive

  metadata:
    name: Publish Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: info
    - name: Set publish_info
      id: publish_info
      run: |
        release_id=$(cat info/release_id)
        echo "release_id=$release_id" >> $GITHUB_OUTPUT
    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.publish_info.outputs.release_id }}
    - uses: eregon/keep-last-n-releases@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        n: 10
