name: Android CI

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    name: Create GitHub Release APKs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: "0"
    - name: set up JDK 21
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create version tag
      id: create_tag
      run: |
        app=$(./gradlew -q printAppName)
        ver=$(./gradlew -q printAppVersion)
        tag=release-$ver-$(date +%Y%m%d-%H%M%S)
        echo "ver=$ver" >> $GITHUB_OUTPUT
        echo "tag=$tag" >> $GITHUB_OUTPUT
        echo "apkRelUName=$app-$ver-release-unsigned.apk" >> $GITHUB_OUTPUT
        echo "apkRelSName=$app-$ver-signedRelease.apk" >> $GITHUB_OUTPUT
        echo "apkDebName=$app-$ver-debug.apk" >> $GITHUB_OUTPUT
        echo "apkRelUPath=./app/build/outputs/apk/release/$app-$ver-release-unsigned.apk" >> $GITHUB_OUTPUT
        echo "apkRelSPath=./app/build/outputs/apk/signedRelease/$app-$ver-signedRelease.apk" >> $GITHUB_OUTPUT
        echo "apkDebPath=./app/build/outputs/apk/debug/$app-$ver-debug.apk" >> $GITHUB_OUTPUT

    - name: Create signing info
      id: create_signing
      if: ${{ env.JKS != '' }}
      run: |
        ApplicationName=$(./gradlew -q printAppName)
        echo -n "${JKS}" | base64 --decode > ./${ApplicationName}.jks
        echo "keystore=${PWD}/${ApplicationName}.jks" > ./${ApplicationName}.signing
        echo "keystore.password=${JKS_PWD}" >> ./${ApplicationName}.signing
        echo "keyAlias=${JKS_KEY_ALIAS}" >> ./${ApplicationName}.signing
        echo "keyPassword=${JKS_KEY_PWD}" >> ./${ApplicationName}.signing
      shell: bash
      env:
        JKS: ${{ secrets.JKS}}
        JKS_PWD: ${{ secrets.JKS_PWD}}
        JKS_KEY_ALIAS: ${{ secrets.JKS_KEY_ALIAS}}
        JKS_KEY_PWD: ${{ secrets.JKS_KEY_PWD}}

    - name: Build with Gradle
      run: ./gradlew --warning-mode all build

    - name: Display artifacts
      run: find . -name '*.apk'
      working-directory: .

    - name: Create Release
      id: create_release
      uses: comnoco/create-release-action@v2.0.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: ${{ steps.create_tag.outputs.tag }}
        draft: false
        prerelease: false

    - name: Upload signed release
      uses: shogo82148/actions-upload-release-asset@v1.7.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.create_tag.outputs.apkRelSPath }}
        asset_name: ${{ steps.create_tag.outputs.apkRelSName }}
        asset_content_type: application/vnd.android.package-archive

    - name: Upload release
      uses: shogo82148/actions-upload-release-asset@v1.7.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.create_tag.outputs.apkRelUPath }}
        asset_name: ${{ steps.create_tag.outputs.apkreleaseuname }}
        asset_content_type: application/vnd.android.package-archive

    - name: Upload debug
      uses: shogo82148/actions-upload-release-asset@v1.7.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.create_tag.outputs.apkDebPath }}
        asset_name: ${{ steps.create_tag.outputs.apkDebName }}
        asset_content_type: application/vnd.android.package-archive

    - uses: eregon/publish-release@v1.0.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
    - uses: eregon/keep-last-n-releases@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        n: 10
